//go:build ignore
// +build ignore

package main

import (
	"flag"
	"fmt"
	"os"
	"text/template"
	"time"
)

const (
	fileName   = "version_gen.go"
	versionKey = "RELEASE_VERSION"
)

var packageTemplate = template.Must(template.New("version").Parse(`// Code generated by go generate; DO NOT EDIT.

package version

const Version = "{{ .Version}}"
`))

func main() {
	version := os.Getenv(versionKey)
	file, err := os.Create(fileName)

	if err != nil {
		fmt.Errorf("unable create file %v")
	}

	defer file.Close()

	packageTemplate.Execute(file, struct {
		Timestamp time.Time
		Version   string
	}{
		Timestamp: time.Now(),
		Version:   ver,
	})
}
