name: GitHub Actions Local Script Test
on: [push]
jobs:
  Local-Script-Job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: ./scripts/script.sh