name: Release
on: 
  push:
    branches:
      - main
jobs:
  Release_Job:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Fetching GO version from repo
        run: echo "GO_VERSION=$(cat .go-version)" >> $GITHUB_ENV
      - name: Setup GO environment
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Running integration tests
        run: go test -v  -coverprofile=coverage.out ./...
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
      - name: Fetch code coverage
        run: go tool cover -func coverage.out
      - name: Create Release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v2"
          release_name: "v2"
          draft: false
          prerelease: false