name: Unit Test
on: 
  push:
    branches:
      - testingbranch
jobs:
  Run-Unit-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: git tag $(cat .sdk-version)
      - run: git push origin $(cat .sdk-version)
