name: CHECK SECRET
on: [push]
jobs:
  Checking-Secret:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: check-secret
        env:
          MY_TEST_SECRET: ${{ env.MY_SECRET }}
        run: |
          echo $MY_SECRET
          echo $MY_TEST_SECRET
