name: CHECK SECRET
on: [push]
jobs:
  Run-Unit-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "GO_VERSION=$(cat .go-version)" >> $GITHUB_ENV
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: echo "------------- Starting Unit Test -------------"
      - name: Unit Test
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: go test -v -coverpkg=./sdk -coverprofile=coverage.out ./sdk
      - run: go tool cover -func coverage.out
