name: Release_Workflow
on: 
  push:
    tags:
      - 'v*'
jobs:
  Release_Job:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.ref }}
      - name: Create Release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
