name: Test_workflow
on: 
  push:
    branches:
      - 'workflow'
jobs:
  Code_Analysis_Job:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.4.0
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      - 
        name: Fetching GO version from repo
        run: echo "GO_VERSION=$(cat .go-version)" >> $GITHUB_ENV
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      -
        run: echo ${{github.ref}}
      -
        name: Create Release Info
        run: echo "SDK_VERSION=$(cat .sdk-version)" >> $GITHUB_ENV
      - 
        name: Setup git config for creating Tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"
      - 
        name: Update sdk version and create Tag
        run: |
          git tag ${{ env.SDK_VERSION }}
          git push origin ${{ env.SDK_VERSION }}
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2.8.0
        with:
          version: latest
          args: release --rm-dist 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
